modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "nostringsattached"
version = "${version}"
displayName = "No Strings Attached"
authors = "iGalaxy"
description = '''
Hide string and other blocks when not holding them
'''
#logoFile = ""

[[dependencies.nostringsattached]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nostringsattached]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nostringsattached]]
modId = "cloth_config"
mandatory = true
versionRange = "[6,7)"
ordering = "NONE"
side = "BOTH"